#creating install.yml
#location /role/tasks/install.yml

---
- name: Install Apache2
  apt:
    name: apache2
    update_cache: yes
    state: latest

- name: send post installation message
  debug:
    msg: "post installation message your ubstallation is complete"

- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: present
